package com.essamine;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class Ljdbc {
	private static Connection cnt;
	private static Statement stmt;
	private static ResultSet rs;

	public static void main(String args[]) {

		try {
			Class.forName("org.hsqldb.jdbcDriver");

			cnt = DriverManager.getConnection("jdbc:hsqldb:file:data/jdbc_base", "SA", "");

			stmt = cnt.createStatement();

			String create_table = "CREATE TABLE student(id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1), name VARCHAR(30))";
			String insert_toTable = "insert into student(name) values('Amine')";
			String insert_toTable2 = "insert into student(name) values('Saîd')";

			stmt.executeUpdate(create_table);
			stmt.executeUpdate(insert_toTable);
			stmt.executeUpdate(insert_toTable2);

			// display the table content.

			String select = "select * from student";

			rs = stmt.executeQuery(select);

			while (rs.next()) {
				System.out.print("\n" + rs.getString(1) + " - " + rs.getString(2));
			}

			cnt.close();
			stmt.close();
			rs.close();

		} catch (ClassNotFoundException classNotFoundException) {
			System.out.println(classNotFoundException);
		} catch (SQLException sQLException) {
			System.out.println(sQLException);
		}

	}
}
